# ---
# id: ci/npm-publish
# category: ci
# type: template
# name: NPM Publish
# description: Automatically publish to npm when version changes on main branch using OIDC trusted publishing. No token management required. Configure trusted publisher at npmjs.com → Package Settings → Trusted publishing.
# secrets: []
# inputs: []
# triggers: [push]
# variants:
#   - name: standard
#     description: Publishes when package.json version changes on main branch pushes using OIDC
# ---

name: NPM Publish

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build package
        run: bun run build

      - name: Check version change
        id: check
        run: |
          CURRENT_VERSION=$(jq -r '.version' package.json)
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          
          PREVIOUS_VERSION=$(git show HEAD~1:package.json | jq -r '.version')
          echo "previous_version=$PREVIOUS_VERSION" >> $GITHUB_OUTPUT
          
          if [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
            echo "version_changed=true" >> $GITHUB_OUTPUT
            echo "Version changed from $PREVIOUS_VERSION to $CURRENT_VERSION"
          else
            echo "version_changed=false" >> $GITHUB_OUTPUT
            echo "Version unchanged: $CURRENT_VERSION"
          fi

      - name: Setup Node.js for npm publish
        if: steps.check.outputs.version_changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish to npm
        if: steps.check.outputs.version_changed == 'true'
        run: npm publish --access public

      - name: Create GitHub Release
        if: steps.check.outputs.version_changed == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const version = '${{ steps.check.outputs.current_version }}';
            const tag = `v${version}`;
            
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${tag}`,
              sha: context.sha
            });
            
            await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: tag,
              name: `Release ${tag}`,
              body: `Published version ${version} to npm`,
              draft: false,
              prerelease: false
            });

      - name: Post success comment
        if: steps.check.outputs.version_changed == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const version = '${{ steps.check.outputs.current_version }}';
            await github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: `🚀 Successfully published version ${version} to npm!\n\nPackage: @openstaticfish/actionflow@${version}`
            });
