# ---
# id: opencode/opencode-nix
# category: opencode
# type: set
# name: OpenCode Slash Commands (Nix)
# description: Responds to /oc and /opencode commands using Nix environment
# secrets:
#   - name: KIMI_API_KEY
#     description: API key for OpenCode AI service
#     required: true
# inputs: []
# triggers: [issue_comment, pull_request_review_comment]
# variants:
#   - name: nix
#     description: Uses Nix for reproducible environment
# ---

name: OpenCode Slash Commands

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  handle-command:
    runs-on: ubuntu-latest
    if: github.event.comment.body =~ /^\/(oc|opencode)\b/
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16

      - name: Cache Nix store
        uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('flake.nix', 'flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size: 1G

      - name: Parse command
        id: parse
        run: |
          nix develop --command bash -c '
            COMMENT_BODY="${{ github.event.comment.body }}"
            
            if [[ "$COMMENT_BODY" =~ ^/oc\s*(.*) ]]; then
              COMMAND="${BASH_REMATCH[1]}"
            elif [[ "$COMMENT_BODY" =~ ^/opencode\s*(.*) ]]; then
              COMMAND="${BASH_REMATCH[1]}"
            fi
            
            echo "command=$COMMAND" >> $GITHUB_OUTPUT
            echo "Parsed command: $COMMAND"
          '

      - name: Gather context
        id: context
        run: |
          if [ "${{ github.event.issue.number }}" != "" ]; then
            echo "type=issue" >> $GITHUB_OUTPUT
            echo "number=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT
          else
            echo "type=pr" >> $GITHUB_OUTPUT
            echo "number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          fi

      - name: Run OpenCode AI
        env:
          KIMI_API_KEY: ${{ secrets.KIMI_API_KEY }}
          COMMAND: ${{ steps.parse.outputs.command }}
        run: |
          nix develop --command bash -c '
            PROMPT=$(cat <<EOF
You are an AI assistant helping with a GitHub repository. 

Command: $COMMAND
Context: ${{ steps.context.outputs.type }} #${{ steps.context.outputs.number }}
Repository: ${{ github.repository }}

Please provide a helpful response to the user'\''s command.
EOF
)
            
            curl -X POST https://api.opencode.ai/v1/chat/completions \
              -H "Authorization: Bearer $KIMI_API_KEY" \
              -H "Content-Type: application/json" \
              -d "{
                \"model\": \"kimi-latest\",
                \"messages\": [{\"role\": \"user\", \"content\": $(echo "$PROMPT" | jq -Rs .)}]
              }" > response.json
            
            cat response.json | jq -r ".choices[0].message.content" > response.txt
          '

      - name: Post response
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const response = fs.readFileSync('response.txt', 'utf8');
            const reply = `🤖 **OpenCode AI**\n\n${response}`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.context.outputs.number }},
              body: reply
            });
