# ---
# id: opencode/opencode
# category: opencode
# type: set
# name: OpenCode AI Slash Commands
# description: OpenCode AI slash command handler (/oc, /opencode)
# secrets:
#   - name: KIMI_API_KEY
#     description: API key for OpenCode AI service
#     required: true
# inputs: []
# triggers: [issue_comment, pull_request_review_comment]
# variants:
#   - name: standard
#     description: Uses OpenCode GitHub Action
# ---

name: OpenCode AI Slash Commands

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  opencode:
    if: |
      contains(github.event.comment.body, ' /oc') ||
      startsWith(github.event.comment.body, '/oc') ||
      contains(github.event.comment.body, ' /opencode') ||
      startsWith(github.event.comment.body, '/opencode')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run opencode
        uses: anomalyco/opencode/github@latest
        env:
          KIMI_API_KEY: ${{ secrets.KIMI_API_KEY }}
        with:
          model: kimi-for-coding/k2p5
